[2025-10-14 23:40:02,148]:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<
[2025-10-14 23:40:02,148]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-14 23:40:02,148]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-14 23:40:02,148]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-14 23:40:02,148]:INFO:common:created directory at: artifacts
[2025-10-14 23:40:02,148]:INFO:common:created directory at: artifacts/data_ingestion
[2025-10-14 23:40:03,167]:INFO:data_ingestion:file: artifacts/data_ingestion/data.zip downloaded with following info: Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: D70A:3AF089:1AEBE4:393E7F:68EE8E41
Accept-Ranges: bytes
Date: Tue, 14 Oct 2025 18:10:03 GMT
Via: 1.1 varnish
X-Served-By: cache-del21730-DEL
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1760465403.842830,VS0,VE339
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: ef5f5f0fece2dae4f331ac6a7df2c2bb2cbf0348
Expires: Tue, 14 Oct 2025 18:15:03 GMT
Source-Age: 0


[2025-10-14 23:40:03,185]:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<
[2025-10-16 00:03:24,243]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-16 00:03:24,247]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-16 00:03:24,249]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-16 00:03:24,250]:INFO:common:created directory at: artifacts
[2025-10-16 00:03:24,251]:INFO:common:created directory at: artifacts/data_validation
[2025-10-16 00:06:47,857]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-16 00:06:47,858]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-16 00:06:47,861]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-16 00:06:47,861]:INFO:common:created directory at: artifacts
[2025-10-16 00:06:47,861]:INFO:common:created directory at: artifacts/data_validation
[2025-10-16 00:09:37,502]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-16 00:09:37,504]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-16 00:09:37,505]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-16 00:09:37,508]:INFO:common:created directory at: artifacts
[2025-10-16 00:09:37,508]:INFO:common:created directory at: artifacts/data_validation
[2025-10-16 00:11:48,430]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-16 00:11:48,431]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-16 00:11:48,433]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-16 00:11:48,433]:INFO:common:created directory at: artifacts
[2025-10-16 00:11:48,433]:INFO:common:created directory at: artifacts/data_validation
[2025-10-16 00:22:33,059]:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<
[2025-10-16 00:22:33,059]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-16 00:22:33,059]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-16 00:22:33,059]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-16 00:22:33,059]:INFO:common:created directory at: artifacts
[2025-10-16 00:22:33,059]:INFO:common:created directory at: artifacts/data_ingestion
[2025-10-16 00:22:33,059]:INFO:data_ingestion:file already exists of size
[2025-10-16 00:22:33,100]:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<
[2025-10-16 00:22:33,101]:INFO:main:>>>>>> stage Data Validation stage started <<<<<<
[2025-10-16 00:22:33,101]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-16 00:22:33,102]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-16 00:22:33,103]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-16 00:22:33,103]:INFO:common:created directory at: artifacts
[2025-10-16 00:22:33,104]:INFO:common:created directory at: artifacts/data_validation
[2025-10-16 00:22:33,139]:INFO:main:>>>>>> stage Data Validation stage completed <<<<<<
[2025-10-16 22:54:32,011]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-16 22:54:32,012]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-16 22:54:32,014]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-16 22:54:32,015]:INFO:common:created directory at: artifacts
[2025-10-16 22:54:32,016]:INFO:common:created directory at: artifacts/data_transformation
[2025-10-16 22:54:43,602]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-16 22:54:43,604]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-16 22:54:43,604]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-16 22:54:43,604]:INFO:common:created directory at: artifacts
[2025-10-16 22:54:43,604]:INFO:common:created directory at: artifacts/data_transformation
[2025-10-16 22:54:43,631]:INFO:215215251:Splitted data into trainning and test split
[2025-10-16 22:54:43,631]:INFO:215215251:(1199, 12)
[2025-10-16 22:54:43,631]:INFO:215215251:(400, 12)
[2025-10-16 23:06:56,277]:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<
[2025-10-16 23:06:56,277]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-16 23:06:56,277]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-16 23:06:56,277]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-16 23:06:56,277]:INFO:common:created directory at: artifacts
[2025-10-16 23:06:56,277]:INFO:common:created directory at: artifacts/data_ingestion
[2025-10-16 23:06:56,277]:INFO:data_ingestion:file already exists of size
[2025-10-16 23:06:56,323]:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<
[2025-10-16 23:06:56,323]:INFO:main:>>>>>> stage Data Validation stage started <<<<<<
[2025-10-16 23:06:56,324]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-16 23:06:56,324]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-16 23:06:56,325]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-16 23:06:56,325]:INFO:common:created directory at: artifacts
[2025-10-16 23:06:56,326]:INFO:common:created directory at: artifacts/data_validation
[2025-10-16 23:06:56,358]:INFO:main:>>>>>> stage Data Validation stage completed <<<<<<
[2025-10-16 23:06:56,358]:INFO:main:>>>>>> stage Data Transformation stage started <<<<<<
[2025-10-16 23:06:56,359]:INFO:data_transformation_pipeline:>>>>>> stage Data Transformation stage skipped <<<<<<
[2025-10-16 23:06:56,359]:ERROR:main:Data validation failed
Traceback (most recent call last):
  File "D:\Desktop\MLOPS\DataScienceProject\main.py", line 31, in <module>
    data_transformation.initiate_data_transformation()
  File "D:\Desktop\MLOPS\DataScienceProject\src\datascienceproject\pipeline\data_transformation_pipeline.py", line 27, in initiate_data_transformation
    raise e
  File "D:\Desktop\MLOPS\DataScienceProject\src\datascienceproject\pipeline\data_transformation_pipeline.py", line 24, in initiate_data_transformation
    raise Exception("Data validation failed")
Exception: Data validation failed
[2025-10-16 23:08:54,546]:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<
[2025-10-16 23:08:54,546]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-16 23:08:54,546]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-16 23:08:54,546]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-16 23:08:54,546]:INFO:common:created directory at: artifacts
[2025-10-16 23:08:54,546]:INFO:common:created directory at: artifacts/data_ingestion
[2025-10-16 23:08:54,546]:INFO:data_ingestion:file already exists of size
[2025-10-16 23:08:54,546]:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<
[2025-10-16 23:08:54,546]:INFO:main:>>>>>> stage Data Validation stage started <<<<<<
[2025-10-16 23:08:54,546]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-16 23:08:54,555]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-16 23:08:54,556]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-16 23:08:54,556]:INFO:common:created directory at: artifacts
[2025-10-16 23:08:54,556]:INFO:common:created directory at: artifacts/data_validation
[2025-10-16 23:08:54,590]:INFO:main:>>>>>> stage Data Validation stage completed <<<<<<
[2025-10-16 23:08:54,591]:INFO:main:>>>>>> stage Data Transformation stage started <<<<<<
[2025-10-16 23:08:54,592]:INFO:data_transformation_pipeline:>>>>>> stage Data Transformation stage skipped <<<<<<
[2025-10-16 23:08:54,593]:ERROR:main:Data validation failed
Traceback (most recent call last):
  File "D:\Desktop\MLOPS\DataScienceProject\main.py", line 31, in <module>
    data_transformation.initiate_data_transformation()
  File "D:\Desktop\MLOPS\DataScienceProject\src\datascienceproject\pipeline\data_transformation_pipeline.py", line 27, in initiate_data_transformation
    raise e
  File "D:\Desktop\MLOPS\DataScienceProject\src\datascienceproject\pipeline\data_transformation_pipeline.py", line 24, in initiate_data_transformation
    raise Exception("Data validation failed")
Exception: Data validation failed
[2025-10-16 23:09:24,905]:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<
[2025-10-16 23:09:24,906]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-16 23:09:24,906]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-16 23:09:24,906]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-16 23:09:24,906]:INFO:common:created directory at: artifacts
[2025-10-16 23:09:24,906]:INFO:common:created directory at: artifacts/data_ingestion
[2025-10-16 23:09:24,906]:INFO:data_ingestion:file already exists of size
[2025-10-16 23:09:24,906]:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<
[2025-10-16 23:09:24,906]:INFO:main:>>>>>> stage Data Validation stage started <<<<<<
[2025-10-16 23:09:24,913]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-16 23:09:24,915]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-16 23:09:24,916]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-16 23:09:24,917]:INFO:common:created directory at: artifacts
[2025-10-16 23:09:24,917]:INFO:common:created directory at: artifacts/data_validation
[2025-10-16 23:09:24,955]:INFO:main:>>>>>> stage Data Validation stage completed <<<<<<
[2025-10-16 23:09:24,955]:INFO:main:>>>>>> stage Data Transformation stage started <<<<<<
[2025-10-16 23:09:24,957]:INFO:data_transformation_pipeline:>>>>>> stage Data Transformation stage skipped <<<<<<
[2025-10-16 23:09:24,957]:ERROR:main:Data transformation failed
Traceback (most recent call last):
  File "D:\Desktop\MLOPS\DataScienceProject\main.py", line 31, in <module>
    data_transformation.initiate_data_transformation()
  File "D:\Desktop\MLOPS\DataScienceProject\src\datascienceproject\pipeline\data_transformation_pipeline.py", line 27, in initiate_data_transformation
    raise e
  File "D:\Desktop\MLOPS\DataScienceProject\src\datascienceproject\pipeline\data_transformation_pipeline.py", line 24, in initiate_data_transformation
    raise Exception("Data transformation failed")
Exception: Data transformation failed
[2025-10-16 23:10:33,389]:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<
[2025-10-16 23:10:33,392]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-16 23:10:33,392]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-16 23:10:33,392]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-16 23:10:33,392]:INFO:common:created directory at: artifacts
[2025-10-16 23:10:33,392]:INFO:common:created directory at: artifacts/data_ingestion
[2025-10-16 23:10:33,392]:INFO:data_ingestion:file already exists of size
[2025-10-16 23:10:33,392]:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<
[2025-10-16 23:10:33,392]:INFO:main:>>>>>> stage Data Validation stage started <<<<<<
[2025-10-16 23:10:33,392]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-16 23:10:33,398]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-16 23:10:33,398]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-16 23:10:33,399]:INFO:common:created directory at: artifacts
[2025-10-16 23:10:33,399]:INFO:common:created directory at: artifacts/data_validation
[2025-10-16 23:10:33,434]:INFO:main:>>>>>> stage Data Validation stage completed <<<<<<
[2025-10-16 23:10:33,434]:INFO:main:>>>>>> stage Data Transformation stage started <<<<<<
[2025-10-16 23:10:33,435]:INFO:data_transformation_pipeline:>>>>>> stage Data Transformation stage skipped <<<<<<
[2025-10-16 23:10:33,435]:ERROR:main:Data transformation failed
Traceback (most recent call last):
  File "D:\Desktop\MLOPS\DataScienceProject\main.py", line 31, in <module>
    data_transformation.initiate_data_transformation()
  File "D:\Desktop\MLOPS\DataScienceProject\src\datascienceproject\pipeline\data_transformation_pipeline.py", line 27, in initiate_data_transformation
    raise e
  File "D:\Desktop\MLOPS\DataScienceProject\src\datascienceproject\pipeline\data_transformation_pipeline.py", line 24, in initiate_data_transformation
    raise Exception("Data transformation failed")
Exception: Data transformation failed
[2025-10-16 23:10:59,301]:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<
[2025-10-16 23:10:59,301]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-16 23:10:59,301]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-16 23:10:59,301]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-16 23:10:59,301]:INFO:common:created directory at: artifacts
[2025-10-16 23:10:59,301]:INFO:common:created directory at: artifacts/data_ingestion
[2025-10-16 23:10:59,301]:INFO:data_ingestion:file already exists of size
[2025-10-16 23:10:59,301]:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<
[2025-10-16 23:10:59,301]:INFO:main:>>>>>> stage Data Validation stage started <<<<<<
[2025-10-16 23:10:59,313]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-16 23:10:59,313]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-16 23:10:59,314]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-16 23:10:59,314]:INFO:common:created directory at: artifacts
[2025-10-16 23:10:59,314]:INFO:common:created directory at: artifacts/data_validation
[2025-10-16 23:10:59,345]:INFO:main:>>>>>> stage Data Validation stage completed <<<<<<
[2025-10-16 23:10:59,345]:INFO:main:>>>>>> stage Data Transformation stage started <<<<<<
[2025-10-16 23:10:59,345]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-16 23:10:59,345]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-16 23:10:59,345]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-16 23:10:59,345]:INFO:common:created directory at: artifacts
[2025-10-16 23:10:59,345]:INFO:common:created directory at: artifacts/data_transformation
[2025-10-16 23:10:59,362]:INFO:data_tranformation:Splitted data into trainning and test split
[2025-10-16 23:10:59,362]:INFO:data_tranformation:(1199, 12)
[2025-10-16 23:10:59,362]:INFO:data_tranformation:(400, 12)
[2025-10-16 23:10:59,362]:INFO:data_transformation_pipeline:>>>>>> stage Data Transformation stage completed <<<<<<
[2025-10-16 23:10:59,362]:INFO:main:>>>>>> stage Data Transformation stage completed <<<<<<
[2025-10-17 21:58:55,790]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-17 21:58:55,792]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-17 21:58:55,795]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-17 21:58:55,795]:INFO:common:created directory at: artifacts
[2025-10-17 21:58:55,795]:INFO:common:created directory at: artifacts/model_trainer
[2025-10-17 21:59:22,877]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-17 21:59:22,878]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-17 21:59:22,879]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-17 21:59:22,881]:INFO:common:created directory at: artifacts
[2025-10-17 21:59:22,881]:INFO:common:created directory at: artifacts/model_trainer
[2025-10-17 21:59:59,485]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-17 21:59:59,487]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-17 21:59:59,489]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-17 21:59:59,490]:INFO:common:created directory at: artifacts
[2025-10-17 21:59:59,492]:INFO:common:created directory at: artifacts/model_trainer
[2025-10-17 21:59:59,501]:INFO:3511284925:Model is trained and saved at artifacts/model_trainer
[2025-10-17 22:11:08,132]:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<
[2025-10-17 22:11:08,132]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-17 22:11:08,132]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-17 22:11:08,132]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-17 22:11:08,132]:INFO:common:created directory at: artifacts
[2025-10-17 22:11:08,132]:INFO:common:created directory at: artifacts/data_ingestion
[2025-10-17 22:11:08,132]:INFO:data_ingestion:file already exists of size
[2025-10-17 22:11:08,167]:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<
[2025-10-17 22:11:08,167]:INFO:main:>>>>>> stage Data Validation stage started <<<<<<
[2025-10-17 22:11:08,168]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-17 22:11:08,168]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-17 22:11:08,170]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-17 22:11:08,171]:INFO:common:created directory at: artifacts
[2025-10-17 22:11:08,171]:INFO:common:created directory at: artifacts/data_validation
[2025-10-17 22:11:08,201]:INFO:main:>>>>>> stage Data Validation stage completed <<<<<<
[2025-10-17 22:11:08,202]:INFO:main:>>>>>> stage Data Transformation stage started <<<<<<
[2025-10-17 22:11:08,220]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-17 22:11:08,221]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-17 22:11:08,222]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-17 22:11:08,222]:INFO:common:created directory at: artifacts
[2025-10-17 22:11:08,222]:INFO:common:created directory at: artifacts/data_transformation
[2025-10-17 22:11:08,237]:INFO:data_tranformation:Splitted data into trainning and test split
[2025-10-17 22:11:08,237]:INFO:data_tranformation:(1199, 12)
[2025-10-17 22:11:08,237]:INFO:data_tranformation:(400, 12)
[2025-10-17 22:11:08,237]:INFO:data_transformation_pipeline:>>>>>> stage Data Transformation stage completed <<<<<<
[2025-10-17 22:11:08,237]:INFO:main:>>>>>> stage Data Transformation stage completed <<<<<<
[2025-10-17 22:11:08,237]:INFO:main:>>>>>> stage Model Trainer stage started <<<<<<
[2025-10-17 22:11:08,239]:INFO:common:yaml file: config\config.yaml loaded successfully
[2025-10-17 22:11:08,239]:INFO:common:yaml file: params.yaml loaded successfully
[2025-10-17 22:11:08,240]:INFO:common:yaml file: schema.yaml loaded successfully
[2025-10-17 22:11:08,241]:INFO:common:created directory at: artifacts
[2025-10-17 22:11:08,241]:INFO:common:created directory at: artifacts/model_trainer
[2025-10-17 22:11:08,295]:INFO:model_trainer:Model is trained and saved at artifacts/model_trainer
[2025-10-17 22:11:08,295]:INFO:main:>>>>>> stage Model Trainer stage completed <<<<<<
